# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/portfolio-analysis',
                'doc_host': 'https://rsp34.github.io',
                'git_url': 'https://github.com/rsp34/portfolio-analysis',
                'lib_path': 'portfolio_analysis'},
  'syms': {'portfolio_analysis.core': {'portfolio_analysis.core.foo': ('core.html#foo', 'portfolio_analysis/core.py')}}}